### ISSUE TITLE
Not Complaint just have no way to get in contact with you /feedback 

### ISSUE THREAD

**Issue by buim16** [jnpl95/Timelapse#14]
Hey bro,

First I just want to say the trainer you’ve created is amazing. Really well done and works great. I’ve used it for many hours and I would like to donate some money to you for the help you’ve gave out. I have no way of communicating with you but if you could possibly give me a way . 

Thanks !

**Comment by jnpl95** [comment]
Hey sorry I just put my email on my profile page. Didn't realize it wasn't there. You can get it touch with me via email at jnpl95@gmail.com. Also no need for donations, I coded this because I enjoyed it :)
