### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by SendHelPlz** [jnpl95/Timelapse#17]
I mean, there's no .exe or what. help i'm noob :/

**Comment by jnpl95** [comment]
> I mean, there's no .exe or what. help i'm noob :/

Sorry this isn't for you, it was meant for coders & people with reverse engineering experience. Needs to be built as a dll & then injected into a target process using an injector. 

Also this was coded for heavenms which is open source on github, not other servers. I recommend searching elsewhere for what you want, if you want a trainer for currently online v83 servers.
