### ISSUE TITLE
does it work all private server?

### ISSUE THREAD

**Issue by xmaple555** [jnpl95/Timelapse#19]
as title, even the game have updated, does it work again? 

renew: it still works now. and it is very awesome that there are a lot of crazy hack and design the netframe gui in dll file. but i got banned on mapleroyal. so now it need to reverse it to change mac address. well thank anyway for your opened resource. it is very help me understand the detail.

**Comment by skeetermack** [comment]
I cant figure out how to make it work, do i have to compile it? i don't know how to do that, can you help me? SkeeterMack#4415 is my discord

**Comment by benbenlor421234** [comment]
i've downloaded the whole zip file and noticed that there is no exe file or any trainer, what should i do? pls help.

**Comment by jnpl95** [comment]
This is a project that builds a dll that needs to be injected into the target executable file. Solution file is included, just need to install visual studio C++/CLI & .net framework.
