### ISSUE TITLE
The GUI filters tab instability

### ISSUE THREAD

**Issue by Bia10** [jnpl95/Timelapse#9]
While coding the loading mechanics for ListBoxes i noticed that upon calling functions:
bItemFilter_Click
bItemFilterAdd_Click
lbItemFilter_MouseDoubleClick
lbItemSearchLog_MouseDoubleClick

the GUI sometimes crashes this maybe also the case with mob related filter. I have not yet investigated why that happens just noticed it. 
Also this condition seems to be bypassed:
!lbItemFilter->Items->Contains(item + " (" + itemID.ToString() + ")")
you can add multiple items with identical names.

**Comment by jnpl95** [comment]
Thanks! I’ll look into that once I get the chance. Most of the crashes in the past occurred with improper loop management so hopefully this will be an easy bug to fix
